Bug 1614786 - Fixup for ?getFIPSEnv? being unused r=kjacobs
Fixes a regression from Bug 1582169

../../lib/sysinit/nsssysinit.c:153:1: error: ?getFIPSEnv? defined but not used [-Werror=unused-function]